// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: segment.proto

package v1

import (
	v1 "arman-estimation-service/grpc/shared/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PushSegmentRequest Push rpc request
type PushSegmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Segment string `protobuf:"bytes,2,opt,name=segment,proto3" json:"segment,omitempty"`
}

func (x *PushSegmentRequest) Reset() {
	*x = PushSegmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_segment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushSegmentRequest) ProtoMessage() {}

func (x *PushSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_segment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushSegmentRequest.ProtoReflect.Descriptor instead.
func (*PushSegmentRequest) Descriptor() ([]byte, []int) {
	return file_segment_proto_rawDescGZIP(), []int{0}
}

func (x *PushSegmentRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PushSegmentRequest) GetSegment() string {
	if x != nil {
		return x.Segment
	}
	return ""
}

// PushSegmentResponse Push rpc response
type PushSegmentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *v1.Status `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *PushSegmentResponse) Reset() {
	*x = PushSegmentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_segment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushSegmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushSegmentResponse) ProtoMessage() {}

func (x *PushSegmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_segment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushSegmentResponse.ProtoReflect.Descriptor instead.
func (*PushSegmentResponse) Descriptor() ([]byte, []int) {
	return file_segment_proto_rawDescGZIP(), []int{1}
}

func (x *PushSegmentResponse) GetResponse() *v1.Status {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_segment_proto protoreflect.FileDescriptor

var file_segment_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0x0c, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x47, 0x0a, 0x12, 0x50, 0x75, 0x73, 0x68, 0x53, 0x65,
	0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x22,
	0x41, 0x0a, 0x13, 0x50, 0x75, 0x73, 0x68, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x64, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x32, 0x4c, 0x0a, 0x07, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x41, 0x0a,
	0x04, 0x50, 0x75, 0x73, 0x68, 0x12, 0x1b, 0x2e, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x50, 0x75, 0x73, 0x68, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x75, 0x73,
	0x68, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x2a, 0x5a, 0x28, 0x61, 0x72, 0x6d, 0x61, 0x6e, 0x2d, 0x65, 0x73, 0x74, 0x69, 0x6d, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_segment_proto_rawDescOnce sync.Once
	file_segment_proto_rawDescData = file_segment_proto_rawDesc
)

func file_segment_proto_rawDescGZIP() []byte {
	file_segment_proto_rawDescOnce.Do(func() {
		file_segment_proto_rawDescData = protoimpl.X.CompressGZIP(file_segment_proto_rawDescData)
	})
	return file_segment_proto_rawDescData
}

var file_segment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_segment_proto_goTypes = []interface{}{
	(*PushSegmentRequest)(nil),  // 0: segment.PushSegmentRequest
	(*PushSegmentResponse)(nil), // 1: segment.PushSegmentResponse
	(*v1.Status)(nil),           // 2: shared.Status
}
var file_segment_proto_depIdxs = []int32{
	2, // 0: segment.PushSegmentResponse.response:type_name -> shared.Status
	0, // 1: segment.Segment.Push:input_type -> segment.PushSegmentRequest
	1, // 2: segment.Segment.Push:output_type -> segment.PushSegmentResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_segment_proto_init() }
func file_segment_proto_init() {
	if File_segment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_segment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushSegmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_segment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushSegmentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_segment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_segment_proto_goTypes,
		DependencyIndexes: file_segment_proto_depIdxs,
		MessageInfos:      file_segment_proto_msgTypes,
	}.Build()
	File_segment_proto = out.File
	file_segment_proto_rawDesc = nil
	file_segment_proto_goTypes = nil
	file_segment_proto_depIdxs = nil
}
